# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'PopTransitionAndGesture' do
pod 'pop', '~> 1.0.7'
end

target 'PopTransitionAndGestureTests' do

end

