# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
use_frameworks!

target 'CuriosSwift' do

pod 'MJExtension', '~> 0.3.1'

end

target 'CuriosSwiftTests' do

end

