//
//  EMUIKit.h
//  
//
//  Created by Emiaostein on 15/2/23.
//  Copyright (c) 2015 Botai Company. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@class PCGradient;

@interface EMUIKit : NSObject

// Colors
+ (UIColor*)gradientColor;
+ (UIColor*)gradientColor2;

// Gradients
+ (PCGradient*)gradient;

// Drawing Methods
+ (void)drawEM_StarWithFrame: (CGRect)frame color: (UIColor*)color;

// Generated Images
+ (UIImage*)imageOfEM_StarWithFrame: (CGRect)frame color: (UIColor*)color;

@end



@interface PCGradient : NSObject
@property(nonatomic, readonly) CGGradientRef CGGradient;
- (CGGradientRef)CGGradient NS_RETURNS_INNER_POINTER;

+ (instancetype)gradientWithColors: (NSArray*)colors locations: (const CGFloat*)locations;
+ (instancetype)gradientWithStartingColor: (UIColor*)startingColor endingColor: (UIColor*)endingColor;

@end
